[versions]
kotlin = "2.2.10"
springBoot = "3.5.3"
ktlint = "13.1.0"
springmockk = "4.0.2"
kotlin-logging = "7.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin"}
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot"}
spring-boot-starter-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
ninjasquad-springmocck = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }